"""claude-oneclick: VPN-style toggle to route Claude Code to custom model endpoints."""

# Static version. The "real" version users see is augmented at install time
# with the commit SHA via `_buildinfo.py` (written by `_post_install`).
__base_version__ = "0.1.0"


def _read_build_sha() -> str | None:
    """Return the commit SHA the install was built/extracted from, if known.

    `_buildinfo.py` is generated by `claude-oneclick _post_install` (and by
    install.sh / install.ps1). It is *not* git-tracked. So:
      - Git checkout: install.sh writes `git rev-parse HEAD`.
      - ZIP install:  install.sh writes the latest SHA fetched from
        github.com at install time.
      - Bare-clone with no install ever run: returns None and we fall
        back to live `git rev-parse` (handled by updater.check()).
    """
    try:
        from claude_oneclick import _buildinfo  # type: ignore
        sha = getattr(_buildinfo, "COMMIT_SHA", None)
        return sha if isinstance(sha, str) and sha else None
    except ImportError:
        return None


def _resolve_version() -> str:
    sha = _read_build_sha()
    if sha:
        return f"{__base_version__}+{sha[:7]}"
    return __base_version__


__version__ = _resolve_version()
