"""Shell rc + env.sh management.

Strategy:

* We never edit the user's rc files except to insert a single `source` line
  inside our marker block. All real env-var logic lives in `env.sh`, which
  we own end-to-end.
* When the toggle is OFF (or nothing is configured) `env.sh` exports nothing,
  so a shell that sources it is identical to one that doesn't.
* When ON, `env.sh` exports `ANTHROPIC_BASE_URL`, `ANTHROPIC_AUTH_TOKEN`,
  `ANTHROPIC_API_KEY`, `ANTHROPIC_MODEL`, and `ANTHROPIC_SMALL_FAST_MODEL`.
"""
from __future__ import annotations

import os
import shlex
from pathlib import Path
from typing import Any

from claude_oneclick.config import get_preset, load
from claude_oneclick.paths import (
    SHELL_BEGIN,
    SHELL_END,
    config_dir,
    env_file,
    ensure_dirs,
)


# ---------- env.sh -----------------------------------------------------------

def env_for_preset(
    preset: dict[str, Any],
    proxy_host: str,
    proxy_port: int,
    *,
    skip_vscode_login: bool = True,
) -> dict[str, str]:
    """Compute the env-var map for a given (active, enabled) preset."""
    fmt = (preset.get("format") or "openai").lower()
    from claude_oneclick.config import _resolve_api_key
    api_key = _resolve_api_key(preset)
    model = preset.get("model") or ""
    small = preset.get("small_fast_model") or model

    if fmt == "anthropic":
        # Talk to upstream directly.
        base = preset.get("base_url") or ""
        env: dict[str, str] = {}
        if base:
            env["ANTHROPIC_BASE_URL"] = base
        if api_key:
            env["ANTHROPIC_AUTH_TOKEN"] = api_key
            env["ANTHROPIC_API_KEY"] = api_key
        if model:
            env["ANTHROPIC_MODEL"] = model
        if small:
            env["ANTHROPIC_SMALL_FAST_MODEL"] = small
        if skip_vscode_login:
            env["CLAUDE_CODE_SKIP_LOGIN"] = "1"
        return env

    # OpenAI-compatible: route Claude Code through our local translation proxy.
    env = {
        "ANTHROPIC_BASE_URL": f"http://{proxy_host}:{proxy_port}",
        # Claude Code requires *something* in this var; the proxy ignores it
        # and uses the upstream key from config.json instead.
        "ANTHROPIC_AUTH_TOKEN": "claude-oneclick",
        "ANTHROPIC_API_KEY": "claude-oneclick",
    }
    if model:
        env["ANTHROPIC_MODEL"] = model
    if small:
        env["ANTHROPIC_SMALL_FAST_MODEL"] = small
    if skip_vscode_login:
        # Tells the Claude Code CLI / VSCode extension to authenticate
        # using ANTHROPIC_AUTH_TOKEN directly and skip the OAuth login
        # flow. This is what makes the toggle "just work" without the
        # user having to log into Anthropic when they're using a custom
        # provider.
        env["CLAUDE_CODE_SKIP_LOGIN"] = "1"
    return env


def render_env_sh(env: dict[str, str]) -> str:
    lines = [
        "# Auto-generated by claude-oneclick. Do not edit; run `claude-oneclick`",
        "# (or use the web UI) to change. Sourced from your shell rc files.",
        "",
    ]
    if not env:
        lines.append("# (toggle is OFF — nothing exported)")
        lines.append("")
        return "\n".join(lines)
    for k, v in env.items():
        lines.append(f"export {k}={shlex.quote(v)}")
    lines.append("")
    return "\n".join(lines)


def write_env_sh() -> dict[str, str]:
    """Recompute env.sh from current config + state. Returns the env map."""
    ensure_dirs()
    cfg = load()
    enabled = bool(cfg.get("enabled"))
    active = cfg.get("active") or "anthropic"
    preset = get_preset(active, cfg) or {}
    proxy = cfg.get("proxy", {})

    if not enabled or active == "anthropic":
        env: dict[str, str] = {}
    else:
        env = env_for_preset(
            preset,
            proxy.get("host", "127.0.0.1"),
            int(proxy.get("port", 47824)),
            skip_vscode_login=bool(cfg.get("skip_vscode_login", True)),
        )

    env_file().write_text(render_env_sh(env), encoding="utf-8")
    return env


# ---------- rc-file injection ------------------------------------------------

_RC_CANDIDATES = [
    "~/.bashrc",
    "~/.bash_profile",
    "~/.zshrc",
    "~/.profile",
]


def _existing_rcs() -> list[Path]:
    out: list[Path] = []
    for c in _RC_CANDIDATES:
        p = Path(os.path.expanduser(c))
        if p.exists():
            out.append(p)
    # If none exist, still create ~/.profile so we have somewhere to hook.
    if not out:
        p = Path(os.path.expanduser("~/.profile"))
        p.touch()
        out.append(p)
    return out


def _block(env_path: Path) -> str:
    return (
        f"\n{SHELL_BEGIN}\n"
        f"# Sourced by claude-oneclick. Toggle env via `claude-oneclick on|off`.\n"
        f'[ -f "{env_path}" ] && . "{env_path}"\n'
        f"{SHELL_END}\n"
    )


def _strip_block(text: str) -> str:
    out_lines: list[str] = []
    skipping = False
    for line in text.splitlines(keepends=True):
        if line.strip() == SHELL_BEGIN:
            skipping = True
            continue
        if line.strip() == SHELL_END:
            skipping = False
            continue
        if not skipping:
            out_lines.append(line)
    return "".join(out_lines)


def install_shell_hook() -> list[Path]:
    ensure_dirs()
    env_path = env_file()
    if not env_path.exists():
        env_path.write_text(render_env_sh({}), encoding="utf-8")
    touched: list[Path] = []
    block = _block(env_path)
    for rc in _existing_rcs():
        text = rc.read_text(encoding="utf-8") if rc.exists() else ""
        stripped = _strip_block(text)
        # Avoid trailing blank-line drift.
        if stripped and not stripped.endswith("\n"):
            stripped += "\n"
        new = stripped + block
        if new != text:
            rc.write_text(new, encoding="utf-8")
            touched.append(rc)
    return touched


def uninstall_shell_hook() -> list[Path]:
    touched: list[Path] = []
    for c in _RC_CANDIDATES:
        rc = Path(os.path.expanduser(c))
        if not rc.exists():
            continue
        text = rc.read_text(encoding="utf-8")
        stripped = _strip_block(text)
        if stripped != text:
            rc.write_text(stripped, encoding="utf-8")
            touched.append(rc)
    return touched
