"""Windows backend for system-wide env injection.

Three layers, applied together for maximum coverage:

1. ``setx KEY VALUE``  — writes ``HKCU\\Environment`` and broadcasts
   ``WM_SETTINGCHANGE``. New processes spawned from Explorer (VSCode,
   Claude Code, terminals) inherit it. This is the Windows analogue of
   editing ``~/.bashrc`` and is what "applies system-wide" means here.

2. PowerShell ``$PROFILE``  — for already-open PowerShell sessions, we
   inject a marker block into ``Documents\\PowerShell\\Microsoft.PowerShell_profile.ps1``
   that ``. ``-sources our ``env.ps1``. Toggle OFF clears env.ps1's body.

3. CMD ``AutoRun``  — ``HKCU\\Software\\Microsoft\\Command Processor`` ``AutoRun``
   value runs our ``env.cmd`` on every new ``cmd.exe``. Same toggle story.

We never touch the system-scope (``HKLM``) registry — everything is per-user
and reversible without admin rights.
"""
from __future__ import annotations

import os
import platform
import shutil
import subprocess
from pathlib import Path

from claude_oneclick.paths import (
    SHELL_BEGIN,
    SHELL_END,
    config_dir,
    ensure_dirs,
)


def is_windows() -> bool:
    return platform.system() == "Windows"


# ---------- env file rendering ----------------------------------------------

def env_ps1_path() -> Path:
    return config_dir() / "env.ps1"


def env_cmd_path() -> Path:
    return config_dir() / "env.cmd"


def _render_ps1(env: dict[str, str]) -> str:
    head = "# Auto-generated by claude-oneclick. Do not edit.\r\n"
    if not env:
        return head + "# (toggle is OFF - nothing exported)\r\n"
    lines = [head]
    for k, v in env.items():
        # Single-quote string is literal in PowerShell; escape ' -> ''
        esc = v.replace("'", "''")
        lines.append(f"$env:{k} = '{esc}'\r\n")
    return "".join(lines)


def _render_cmd(env: dict[str, str]) -> str:
    head = "@rem Auto-generated by claude-oneclick. Do not edit.\r\n@echo off\r\n"
    if not env:
        return head + "@rem (toggle is OFF - nothing exported)\r\n"
    lines = [head]
    for k, v in env.items():
        # In CMD, "set X=Y" with quoted Y is literal; ^ escapes meta-chars.
        safe = v.replace("^", "^^").replace("&", "^&").replace("|", "^|").replace("<", "^<").replace(">", "^>")
        lines.append(f"set {k}={safe}\r\n")
    return "".join(lines)


def write_env_files(env: dict[str, str]) -> None:
    ensure_dirs()
    env_ps1_path().write_text(_render_ps1(env), encoding="utf-8")
    env_cmd_path().write_text(_render_cmd(env), encoding="utf-8")


# ---------- setx (HKCU\Environment) -----------------------------------------

# Names we manage at the user-environment level. Mirror of
# `vscode.MANAGED_KEYS`.
MANAGED_KEYS = (
    "ANTHROPIC_BASE_URL",
    "ANTHROPIC_AUTH_TOKEN",
    "ANTHROPIC_API_KEY",
    "ANTHROPIC_MODEL",
    "ANTHROPIC_SMALL_FAST_MODEL",
    "CLAUDE_CODE_SKIP_LOGIN",
)


def _run(cmd: list[str]) -> tuple[int, str]:
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    except FileNotFoundError as e:
        return 127, str(e)
    return proc.returncode, (proc.stdout + proc.stderr).strip()


def apply_user_env(env: dict[str, str]) -> list[str]:
    """Set/clear user-scope env vars. Returns a list of human-readable steps."""
    if not is_windows():
        return []
    notes: list[str] = []
    setx = shutil.which("setx") or "setx"
    reg = shutil.which("reg") or "reg"
    # Set the keys we want.
    for k, v in env.items():
        rc, out = _run([setx, k, v])
        notes.append(f"setx {k} ... -> rc={rc}")
    # Delete any managed keys we no longer want.
    wanted = set(env.keys())
    for k in MANAGED_KEYS:
        if k in wanted:
            continue
        rc, _ = _run([reg, "delete", "HKCU\\Environment", "/F", "/V", k])
        if rc == 0:
            notes.append(f"reg delete {k} -> ok")
    return notes


def clear_user_env() -> list[str]:
    return apply_user_env({})


# ---------- $PROFILE / AutoRun injection ------------------------------------

def _ps_profile_paths() -> list[Path]:
    """Both PowerShell 5 (Windows PowerShell) and PowerShell 7 (pwsh)."""
    home = Path.home()
    return [
        home / "Documents" / "WindowsPowerShell" / "Microsoft.PowerShell_profile.ps1",
        home / "Documents" / "PowerShell" / "Microsoft.PowerShell_profile.ps1",
    ]


def _ps_block(env_ps1: Path) -> str:
    return (
        f"\r\n{SHELL_BEGIN}\r\n"
        f"# Sourced by claude-oneclick. Toggle env via `claude-oneclick on|off`.\r\n"
        f'if (Test-Path "{env_ps1}") {{ . "{env_ps1}" }}\r\n'
        f"{SHELL_END}\r\n"
    )


def _strip_block(text: str) -> str:
    out: list[str] = []
    skip = False
    for line in text.splitlines(keepends=True):
        s = line.strip()
        if s == SHELL_BEGIN:
            skip = True
            continue
        if s == SHELL_END:
            skip = False
            continue
        if not skip:
            out.append(line)
    return "".join(out)


def install_powershell_hook() -> list[Path]:
    if not is_windows():
        return []
    ensure_dirs()
    env_ps1 = env_ps1_path()
    if not env_ps1.exists():
        env_ps1.write_text(_render_ps1({}), encoding="utf-8")
    block = _ps_block(env_ps1)
    touched: list[Path] = []
    for p in _ps_profile_paths():
        p.parent.mkdir(parents=True, exist_ok=True)
        text = p.read_text(encoding="utf-8") if p.exists() else ""
        stripped = _strip_block(text)
        if stripped and not stripped.endswith("\r\n"):
            stripped += "\r\n"
        new = stripped + block
        if new != text:
            p.write_text(new, encoding="utf-8")
            touched.append(p)
    return touched


def uninstall_powershell_hook() -> list[Path]:
    if not is_windows():
        return []
    touched: list[Path] = []
    for p in _ps_profile_paths():
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8")
        stripped = _strip_block(text)
        if stripped != text:
            p.write_text(stripped, encoding="utf-8")
            touched.append(p)
    return touched


def install_cmd_autorun() -> bool:
    """Set HKCU\\Software\\Microsoft\\Command Processor\\AutoRun to call env.cmd."""
    if not is_windows():
        return False
    reg = shutil.which("reg") or "reg"
    target = str(env_cmd_path())
    rc, _ = _run([
        reg, "add", "HKCU\\Software\\Microsoft\\Command Processor",
        "/V", "AutoRun", "/T", "REG_EXPAND_SZ", "/D", target, "/F",
    ])
    return rc == 0


def uninstall_cmd_autorun() -> bool:
    if not is_windows():
        return False
    reg = shutil.which("reg") or "reg"
    rc, _ = _run([reg, "delete", "HKCU\\Software\\Microsoft\\Command Processor", "/V", "AutoRun", "/F"])
    return rc == 0
